// Class automatically generated by Dev-C++ New Class wizard

#ifndef CCALCEXCEPTION_H
#define CCALCEXCEPTION_H

#include <exception> // inheriting class's header file

/*
 * any exception
 */
using namespace std; 

/*
class mympi
{
 public:
    static int rank, size;
    static bool flag;
    static double step;
    static int inv_step;
};
*/

class cCalcException : public exception
{
	public:
		// class constructor
		cCalcException(const char* message);
};

#endif // CCALCEXCEPTION_H
