// Class automatically generated by Dev-C++ New Class wizard

#include "ccalcexception.h" // class's header file
#include <stdio.h>

//int mympi::rank, mympi::size;
//bool mympi::flag=false;
//double mympi::step=0.01;
//int mympi::inv_step=100;

// class constructor
cCalcException::cCalcException(const char* message) :
                                     exception()
{
	printf("\n%s\n",message);
}

